version: "3"

services:
    client:
        image: nginx
        ports:
            - 1111:80
        volumes:
            - ./src:/usr/share/nginx/html

    nodejs:
        image: node:14
        working_dir: /app
        volumes:
            - ./src:/app
        command: sh -c "npm install && npm start"