const kanjiData = {
    n5: [
        { id: 1, kanji: "一", meaning: "один", furigana: "いち" },
        { id: 2, kanji: "二", meaning: "два", furigana: "に" },
        { id: 3, kanji: "三", meaning: "три", furigana: "さん" },
        { id: 4, kanji: "四", meaning: "четыре", furigana: "し" },
        { id: 5, kanji: "五", meaning: "пять", furigana: "ご" },
        { id: 6, kanji: "六", meaning: "шесть", furigana: "ろく" },
        { id: 7, kanji: "七", meaning: "семь", furigana: "しち" },
        { id: 8, kanji: "八", meaning: "восемь", furigana: "はち" },
        { id: 9, kanji: "九", meaning: "девять", furigana: "きゅう" },
        { id: 10, kanji: "十", meaning: "десять", furigana: "じゅう" },
        { id: 11, kanji: "百", meaning: "сто" },
        { id: 12, kanji: "千", meaning: "тысяча" },
        { id: 13, kanji: "万", meaning: "десять тысяч" },
        { id: 14, kanji: "円", meaning: "иена" },
        { id: 15, kanji: "時", meaning: "час" },
        { id: 16, kanji: "日", meaning: "день, солнце" },
        { id: 17, kanji: "月", meaning: "месяц, луна" },
        { id: 18, kanji: "火", meaning: "огонь" },
        { id: 19, kanji: "水", meaning: "вода" },
        { id: 20, kanji: "木", meaning: "дерево" },
        { id: 21, kanji: "金", meaning: "золото" },
        { id: 22, kanji: "土", meaning: "земля" },
        { id: 23, kanji: "本", meaning: "книга, истинный" },
        { id: 24, kanji: "人", meaning: "человек" },
        { id: 25, kanji: "年", meaning: "год" },
        { id: 26, kanji: "大", meaning: "большой" },
        { id: 27, kanji: "中", meaning: "внутри, средний" },
        { id: 28, kanji: "長", meaning: "долгий, старший" },
        { id: 29, kanji: "出", meaning: "выходить" },
        { id: 30, kanji: "見", meaning: "смотреть" },
        { id: 31, kanji: "行", meaning: "идти, действовать" },
        { id: 32, kanji: "高", meaning: "высокий" },
        { id: 33, kanji: "前", meaning: "перед, впереди" },
        { id: 34, kanji: "後", meaning: "после, позади" },
        { id: 35, kanji: "小", meaning: "маленький" },
        { id: 36, kanji: "上", meaning: "наверху, вверх" },
        { id: 37, kanji: "下", meaning: "внизу, ниже" },
        { id: 38, kanji: "山", meaning: "гора" },
        { id: 39, kanji: "川", meaning: "река" },
        { id: 40, kanji: "元", meaning: "начало" },
        { id: 41, kanji: "気", meaning: "дух, настроение" },
        { id: 42, kanji: "天", meaning: "небо, небеса" },
        { id: 43, kanji: "私", meaning: "я, мной" },
        { id: 44, kanji: "今", meaning: "сейчас, нынешний" },
        { id: 45, kanji: "右", meaning: "правый" },
        { id: 46, kanji: "左", meaning: "левый" },
        { id: 47, kanji: "分", meaning: "часть, минута" },
        { id: 48, kanji: "友", meaning: "друг" },
        { id: 49, kanji: "力", meaning: "сила" },
        { id: 50, kanji: "学", meaning: "учеба, наука" },
        { id: 51, kanji: "校", meaning: "школа" },
        { id: 52, kanji: "父", meaning: "отец" },
        { id: 53, kanji: "母", meaning: "мать" },
        { id: 54, kanji: "男", meaning: "мужчина" },
        { id: 55, kanji: "女", meaning: "женщина" },
        { id: 56, kanji: "子", meaning: "ребенок" },
        { id: 57, kanji: "先", meaning: "ранее, впереди" },
        { id: 58, kanji: "名", meaning: "имя" },
        { id: 59, kanji: "生", meaning: "жизнь, рождение" },
        { id: 60, kanji: "雨", meaning: "дождь" },
        { id: 61, kanji: "電", meaning: "электричество"},
        { id: 62, kanji: "車", meaning: "автомобиль" },
        { id: 63, kanji: "京", meaning: "столица" }, 
        { id: 64, kanji: "学", meaning: "учиться, наука" },
        { id: 65, kanji: "校", meaning: "школа" },
        { id: 66, kanji: "文", meaning: "письмо, культура" },
        { id: 67, kanji: "字", meaning: "символ, буква" },
        { id: 68, kanji: "新", meaning: "новый" },
        { id: 69, kanji: "古", meaning: "старый" },
        { id: 70, kanji: "間", meaning: "промежуток, интервал" },
        { id: 71, kanji: "方", meaning: "направление, сторона" },
        { id: 72, kanji: "地", meaning: "земля, место" },
        { id: 73, kanji: "海", meaning: "море" },
        { id: 74, kanji: "所", meaning: "место, точка" },
        { id: 75, kanji: "近", meaning: "близко" },
        { id: 76, kanji: "遠", meaning: "далеко" },
        { id: 77, kanji: "物", meaning: "вещь, объект" },
        { id: 78, kanji: "町", meaning: "город, городской район" },
        { id: 79, kanji: "村", meaning: "деревня" },
        { id: 80, kanji: "国", meaning: "страна" },
        { id: 81, kanji: "会", meaning: "встреча, ассоциация" },
        { id: 82, kanji: "社", meaning: "компания, общество" },
        { id: 83, kanji: "話", meaning: "разговор, речь" },
        { id: 84, kanji: "語", meaning: "язык, слово" },
        { id: 85, kanji: "読", meaning: "читать" },
        { id: 86, kanji: "書", meaning: "писать" },
        { id: 87, kanji: "聞", meaning: "слушать" },
        { id: 88, kanji: "言", meaning: "говорить, язык" },
        { id: 89, kanji: "話", meaning: "разговор, речь" },
        { id: 90, kanji: "音", meaning: "звук, шум" },
        { id: 91, kanji: "楽", meaning: "радость, музыка" },
        { id: 92, kanji: "食", meaning: "есть, пища" },
        { id: 93, kanji: "飲", meaning: "пить" },
        { id: 94, kanji: "買", meaning: "покупать" },
        { id: 95, kanji: "売", meaning: "продавать" },
        { id: 96, kanji: "来", meaning: "приходить, следующий" },
        { id: 97, kanji: "帰", meaning: "возвращаться" },
        { id: 98, kanji: "入", meaning: "входить, войти" },
        { id: 99, kanji: "出", meaning: "выходить, выйти" },
        { id: 100, kanji: "持", meaning: "держать, иметь", furigana: "も" },
        { id: 101, kanji: "手", meaning: "рука", furigana: "て" },
        { id: 102, kanji: "足", meaning: "нога, ступня", furigana: "あし" },
        { id: 103, kanji: "目", meaning: "глаз", furigana: "め" },

        
        
        // Добавьте больше иероглифов уровня N5
    ],
    // Добавьте данные для уровней N4, N3, N2 и N1 аналогичным образом
};
